import './TC_DeviceModelsManagementWithRoleAdminAndReturnSuccessfullyResult.cy'
import './TC_AircraftManagementWithRoleAdminAndReturnCreatedDeviceSuccessfully.cy'
import './TC_AiPredictLogErrorWithRoleAnalystAndReturnSuccessfullyPredicted.cy'
import './TC_ResearchFlightIdAndReturnSuccessfullyResearched.cy'