describe('ReviewAnalysisHistoryWithRoleAdminAndReturnSuccessfullyReviewed', () => {
    it('ReviewAnalysisHistoryWithRoleAdminAndReturnSuccessfullyReviewed', () => {
      cy.visit('http://172.25.254.0:10105/login')
      cy.get('input[type = "text"]').type('huynhthehainam.mismart@gmail.com')
          cy.get('input[type = "password"]').type('123456')
          cy.get('.MuiButton-contained').click()
          const sleeptimes = 3000;
          cy.wait(sleeptimes)
    //1. Choose Agriculture Projects
    cy.get('.flex-1 > .MuiButtonBase-root > .material-icons').click()
    cy.wait(sleeptimes)
    cy.get('[href="/apps/projects"] > .MuiListItemText-root > .MuiTypography-root').click()
    cy.wait(sleeptimes)
    //2. Expected Result: Contains(Task name, Created Time, Location and Processing Node)
    cy.get('.muiltr-jvbf1s > .MuiButtonBase-root').should('have.text', 'Task Name')
    cy.wait(sleeptimes)
    cy.get('.MuiTableRow-root > :nth-child(2) > .MuiButtonBase-root').should('have.text', 'Created Time')
    cy.wait(sleeptimes)
    cy.get('.MuiTableRow-root > :nth-child(3) > .MuiButtonBase-root').should('have.text', 'Location')
    cy.wait(sleeptimes)
    cy.get('.muiltr-3195kg > .MuiButtonBase-root').should('have.text', 'Processing Node')
    cy.wait(sleeptimes)
    //3. Open Status Completed
    cy.get(':nth-child(1) > .muiltr-q3j589').click()
    cy.wait(sleeptimes)
    //4. Expected Result: Contains(Manager, Company, Crops, Created on, Area, Stage, Download Asset, View Map and Add Task)
    cy.get(':nth-child(1) > .muiltr-18abb6m').should('have.text', 'Manager: ')
    cy.wait(sleeptimes)
    cy.get(':nth-child(2) > .muiltr-18abb6m').should('have.text', 'Company: ')
    cy.wait(sleeptimes)
    cy.get(':nth-child(3) > .muiltr-18abb6m').should('have.text', 'Crops: ')
    cy.wait(sleeptimes)
    cy.get(':nth-child(4) > .muiltr-18abb6m').should('have.text', 'Created on: ')
    cy.wait(sleeptimes)
    cy.get(':nth-child(5) > .muiltr-18abb6m').should('have.text', 'Area: ')
    cy.wait(sleeptimes)
    cy.get(':nth-child(6) > .muiltr-18abb6m').should('have.text', 'Stage: ')
    cy.wait(sleeptimes)
    cy.get('.muiltr-ffmerx > .MuiButton-text > .MuiTypography-root').should('have.text', 'Download Asset')
    cy.wait(sleeptimes)
    cy.get('.muiltr-q5ygko > .MuiTypography-root').should('have.text', 'View Map' )
    cy.wait(sleeptimes)
    cy.get('.muiltr-u43kzn > .MuiButton-containedPrimary > .MuiTypography-root').should('have.text', 'Add Task')
    cy.wait(sleeptimes)
    //5. Open View Map
    cy.get('.muiltr-q5ygko').click()
    cy.wait(sleeptimes)
    //6. Expected Result: contain(Forestry)
    cy.get('.gap-x-8 > .MuiTypography-root').should('have.text', 'Forestry')
    cy.wait(sleeptimes)
    })
})      