import './TC_CreateReportWithRoleUserAndReturnSuccessfullyGeneratedReport.cy'
import './TC_LogFileAnalystAndReturnSuccessfullyAnalysic.cy'
import './TC_ConfirmLogFileAnalystWithRoleAdminAndReturnSuccessfullyConfirmed.cy'
